### ISSUE TITLE
Wrong data in skills section of API

### ISSUE THREAD

**Issue by amitness** [ujwaldhakal/nepal-it-pool#11]
On the developers.json file, I have listed my skills related to machine learning.

On the response returned by the API, the skills key for my profile lists items different than that. It's showing the skills related to Quality assurance and testing.

Actual entered data:
![image](https://user-images.githubusercontent.com/8587189/69497239-c5235600-0f02-11ea-801c-41424df413cc.png)

API output:
![image](https://user-images.githubusercontent.com/8587189/69497229-acb33b80-0f02-11ea-92db-f892dc0498dc.png)

**Comment by ujwaldhakal** [comment]
Thank you for reporting an issue and it has been resolved .
